version: "3.8"

services:
  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    image: backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network
    env_file:
      - .env
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
volumes:
  mongo-data:

networks:
  app-network:

